# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CodeUI-practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeUI-practice
  pod 'SnapKit', '~> 5.6.0'

end
